# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('path', models.CharField(max_length=256)),
                ('info_path', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TrashContentFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=256)),
                ('file_name', models.CharField(max_length=256)),
                ('file_path', models.CharField(max_length=256)),
                ('trash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trashes.Trash')),
            ],
        ),
    ]
