# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_task', models.CharField(max_length=256)),
                ('file_path', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='trashcontentfiles',
            name='trash',
        ),
        migrations.DeleteModel(
            name='TrashContentFiles',
        ),
    ]
