# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashes', '0005_tasktodo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktodo',
            name='file_task',
            field=models.CharField(choices=[('delete by regex', 'delete by regex'), ('delete by filename', 'delete by filename'), ('recover all trash', 'recover all trash'), ('clear all trash', 'clear all trash'), ('remove files from trash', 'remove files from trash'), ('recover files from trash', 'recover files from trash'), ('remove files from trash by regex', 'remove files from trash by regex'), ('recover files from trash by regex', 'recover files from trash by regex')], default=None, max_length=256),
        ),
    ]
