# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashes', '0008_auto_20170904_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktodo',
            name='task_process',
            field=models.CharField(choices=[('Not done', 'Not done'), ('In process', 'In process'), ('Waiting', 'Waiting'), ('Done', 'Done')], default='Not done', max_length=256),
        ),
    ]
