# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashes', '0014_auto_20170910_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktodo',
            name='maximum_size',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='tasktodo',
            name='maximum_time',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='trash',
            name='maximum_size',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='trash',
            name='maximum_time',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
