# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashes', '0015_auto_20170913_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='maximum_size',
            field=models.PositiveIntegerField(default=1000, max_length=9),
        ),
        migrations.AlterField(
            model_name='trash',
            name='maximum_time',
            field=models.PositiveIntegerField(default=7, max_length=9),
        ),
    ]
