# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trashes', '0018_auto_20170915_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasktodo',
            old_name='force',
            new_name='verbose',
        ),
        migrations.RemoveField(
            model_name='tasktodo',
            name='info_path',
        ),
        migrations.RemoveField(
            model_name='tasktodo',
            name='maximum_size',
        ),
        migrations.RemoveField(
            model_name='tasktodo',
            name='maximum_time',
        ),
    ]
