# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trashes', '0002_auto_20170623_1945'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tasktodo',
            table='task',
        ),
        migrations.AlterModelTable(
            name='trash',
            table='trashes',
        ),
    ]
