# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trashes', '0003_auto_20170623_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktodo',
            name='dry_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasktodo',
            name='force',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasktodo',
            name='info_path',
            field=models.CharField(default=' ', max_length=256),
        ),
        migrations.AddField(
            model_name='tasktodo',
            name='maximum_size',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='tasktodo',
            name='maximum_time',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='tasktodo',
            name='regular',
            field=models.CharField(default=' ', max_length=256),
        ),
        migrations.AddField(
            model_name='tasktodo',
            name='silent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasktodo',
            name='task_is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasktodo',
            name='trash',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trashes.Trash'),
        ),
        migrations.AddField(
            model_name='trash',
            name='maximum_size',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='trash',
            name='maximum_time',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='trash',
            name='policy_size',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trash',
            name='policy_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tasktodo',
            name='file_path',
            field=models.CharField(default=' ', max_length=256),
        ),
        migrations.AlterField(
            model_name='tasktodo',
            name='file_task',
            field=models.CharField(choices=[('delete by regex', 'delete by regex'), ('delete by filename', 'delete by filename'), ('recover all trash', 'recover all trash'), ('clear all trash', 'clear all trash')], default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='trash',
            name='info_path',
            field=models.CharField(default=' ', max_length=256),
        ),
    ]
