# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashes', '0006_auto_20170901_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktodo',
            name='task_is_done',
        ),
        migrations.AddField(
            model_name='tasktodo',
            name='task_process',
            field=models.CharField(choices=[(0, 'Not done'), (1, 'In process'), (2, 'Waiting'), (3, 'Done')], default=0, max_length=256),
        ),
    ]
